name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: configure
      run: ./configure
      
    - name: Setup Java JDK
      uses: actions/setup-java@v1.4.4
      with:
        java-version: 17

    - name: Run make
      run: make
