name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Java JDK
      uses: actions/setup-java@v1.4.4
      with:
        java-version: 17
        
    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1.8.0
      with:
        # The version of LLVM and Clang binaries to install.
        version: "10.0"


    - name: Run make
      run: make
